"""Multi-image patient PDF report (uses built-in QtPrintSupport — no extra deps).

Report layout:
  Cover page  : clinic header, patient info, summary of findings
  Image pages : 2 images per page with tooth label, date, and notes
  Footer      : medical disclaimer on every page

Works offline; output is a single standalone .pdf the dentist can share."""

from datetime import datetime
from PyQt6.QtCore import Qt, QRectF, QMarginsF
from PyQt6.QtGui import QPainter, QFont, QColor, QPageLayout, QPageSize, QPixmap
from PyQt6.QtPrintSupport import QPrinter

from tooth_chart import tooth_name


DISCLAIMER = ("This report is generated by Trident Dental Imaging — a workflow "
              "tool. NOT a certified medical device. Diagnosis must be confirmed "
              "using certified software and clinical examination.")


def _fmt_dt(s):
    if not s:
        return ""
    try:
        return datetime.fromisoformat(s.replace("Z", "")).strftime("%Y-%m-%d %H:%M")
    except Exception:
        return s


def _draw_footer(p, w, h, page_num, total):
    p.save()
    p.setPen(QColor(120, 120, 120))
    p.setFont(QFont("Arial", 7))
    p.drawText(QRectF(40, h - 50, w - 80, 30),
               int(Qt.TextFlag.TextWordWrap | Qt.AlignmentFlag.AlignLeft),
               DISCLAIMER)
    p.setFont(QFont("Arial", 8))
    p.drawText(QRectF(40, h - 20, w - 80, 15),
               Qt.AlignmentFlag.AlignRight, f"Page {page_num} / {total}")
    p.restore()


def _draw_header(p, w, clinic, doctor):
    p.save()
    p.setPen(QColor(0, 0, 0))
    p.setFont(QFont("Arial", 14, QFont.Weight.Bold))
    p.drawText(QRectF(40, 30, w - 80, 25),
               Qt.AlignmentFlag.AlignLeft, clinic or "Dental Clinic")
    if doctor:
        p.setFont(QFont("Arial", 10))
        p.drawText(QRectF(40, 55, w - 80, 18),
                   Qt.AlignmentFlag.AlignLeft, f"Dr. {doctor}")
    p.setPen(QColor(180, 180, 180))
    p.drawLine(40, 80, int(w) - 40, 80)
    p.restore()


def _draw_cover(p, w, h, clinic, doctor, patient, tooth_statuses, image_count):
    _draw_header(p, w, clinic, doctor)
    y = 110
    p.setPen(QColor(0, 0, 0))
    p.setFont(QFont("Arial", 18, QFont.Weight.Bold))
    p.drawText(QRectF(40, y, w - 80, 30),
               Qt.AlignmentFlag.AlignLeft, "Patient Imaging Report")
    y += 40

    p.setFont(QFont("Arial", 11))
    name = f"{patient.get('first_name','')} {patient.get('last_name','')}".strip()
    lines = [
        ("Patient", name or "-"),
        ("Date of Birth", patient.get("date_of_birth") or "-"),
        ("Gender", patient.get("gender") or "-"),
        ("Phone", patient.get("phone") or "-"),
        ("Email", patient.get("email") or "-"),
        ("Report Date", datetime.now().strftime("%Y-%m-%d %H:%M")),
        ("Images Included", str(image_count)),
    ]
    for label, val in lines:
        p.setFont(QFont("Arial", 10, QFont.Weight.Bold))
        p.drawText(QRectF(40, y, 140, 20), Qt.AlignmentFlag.AlignLeft, f"{label}:")
        p.setFont(QFont("Arial", 10))
        p.drawText(QRectF(180, y, w - 220, 20), Qt.AlignmentFlag.AlignLeft, val)
        y += 22

    if patient.get("medical_history"):
        y += 10
        p.setFont(QFont("Arial", 11, QFont.Weight.Bold))
        p.drawText(QRectF(40, y, w - 80, 20),
                   Qt.AlignmentFlag.AlignLeft, "Medical History")
        y += 22
        p.setFont(QFont("Arial", 9))
        p.drawText(QRectF(40, y, w - 80, 120),
                   int(Qt.TextFlag.TextWordWrap | Qt.AlignmentFlag.AlignLeft),
                   patient["medical_history"])
        y += 130

    if tooth_statuses:
        p.setFont(QFont("Arial", 11, QFont.Weight.Bold))
        p.drawText(QRectF(40, y, w - 80, 20),
                   Qt.AlignmentFlag.AlignLeft, "Dental Chart Findings")
        y += 22
        p.setFont(QFont("Arial", 9))
        for fdi in sorted(tooth_statuses.keys()):
            s = tooth_statuses[fdi]
            status = s.get("status", "")
            if status == "healthy":
                continue
            note = s.get("notes") or ""
            line = f"#{fdi} ({tooth_name(fdi).split(' - ')[1].split(' (')[0]}): {status}"
            if note:
                line += f" — {note}"
            p.drawText(QRectF(40, y, w - 80, 16),
                       Qt.AlignmentFlag.AlignLeft, line)
            y += 16
            if y > h - 80:
                break


def _draw_image_block(p, x, y, w, h, img_row, pixmap):
    p.save()
    p.setPen(QColor(200, 200, 200))
    p.drawRect(QRectF(x, y, w, h))

    title_h = 22
    info_h = 40
    img_area_h = h - title_h - info_h - 8

    tooth = img_row.get("tooth_number")
    label = f"Tooth #{tooth} — {tooth_name(int(tooth)).split(' - ')[1].split(' (')[0]}" \
        if tooth else (img_row.get("image_type") or "Image")
    p.setPen(QColor(0, 0, 0))
    p.setFont(QFont("Arial", 10, QFont.Weight.Bold))
    p.drawText(QRectF(x + 6, y + 4, w - 12, title_h),
               Qt.AlignmentFlag.AlignLeft, label)

    if pixmap and not pixmap.isNull():
        scaled = pixmap.scaled(int(w - 12), int(img_area_h),
                               Qt.AspectRatioMode.KeepAspectRatio,
                               Qt.TransformationMode.SmoothTransformation)
        ix = x + (w - scaled.width()) / 2
        iy = y + title_h + 4
        p.drawPixmap(int(ix), int(iy), scaled)

    p.setFont(QFont("Arial", 8))
    p.setPen(QColor(80, 80, 80))
    info_y = y + h - info_h
    p.drawText(QRectF(x + 6, info_y, w - 12, 14),
               Qt.AlignmentFlag.AlignLeft,
               f"Captured: {_fmt_dt(img_row.get('captured_at'))}   "
               f"Type: {img_row.get('image_type') or '-'}")
    notes = (img_row.get("notes") or "").strip()
    if notes:
        p.drawText(QRectF(x + 6, info_y + 14, w - 12, 24),
                   int(Qt.TextFlag.TextWordWrap | Qt.AlignmentFlag.AlignLeft),
                   f"Notes: {notes}")
    p.restore()


def generate_report(out_path, patient, images, tooth_statuses=None,
                    clinic="Dental Clinic", doctor=""):
    """Write a PDF report. `images` is a list of dicts with file_path+metadata."""
    pixmaps = []
    for img in images:
        pm = QPixmap(img.get("file_path", ""))
        pixmaps.append(pm)

    printer = QPrinter(QPrinter.PrinterMode.HighResolution)
    printer.setOutputFormat(QPrinter.OutputFormat.PdfFormat)
    printer.setOutputFileName(out_path)
    printer.setPageSize(QPageSize(QPageSize.PageSizeId.A4))
    printer.setPageOrientation(QPageLayout.Orientation.Portrait)
    printer.setPageMargins(QMarginsF(15, 15, 15, 15), QPageLayout.Unit.Millimeter)

    images_per_page = 2
    total_pages = 1 + max(1, (len(images) + images_per_page - 1) // images_per_page) \
        if images else 1

    painter = QPainter(printer)
    page_rect = printer.pageRect(QPrinter.Unit.DevicePixel)
    w, h = page_rect.width(), page_rect.height()

    _draw_cover(painter, w, h, clinic, doctor, patient,
                tooth_statuses or {}, len(images))
    _draw_footer(painter, w, h, 1, total_pages)

    page_num = 1
    i = 0
    while i < len(images):
        printer.newPage()
        page_num += 1
        _draw_header(painter, w, clinic, doctor)

        top = 100.0
        block_h = (h - top - 60) / images_per_page - 10
        for slot in range(images_per_page):
            if i >= len(images):
                break
            y = top + slot * (block_h + 10)
            _draw_image_block(painter, 40, y, w - 80, block_h,
                              images[i], pixmaps[i])
            i += 1
        _draw_footer(painter, w, h, page_num, total_pages)

    painter.end()
    return out_path
